version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.1-jdk

    working_directory: ~/my-walking-skeleton

    steps:
      # git pull
      - checkout

      # setup testing env
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Login to DockerHub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS

      # Download and cache dependencies
      - restore_cache:
          keys:
            - my-walking-skeleton-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: my-walking-skeleton-{{ checksum "pom.xml" }}

      # package into a jar
      - run: mvn clean package

      # build and push docker image to docker hub
      - run: mvn clean compile jib:build -Dimage=tomspencercodurance/my-walking-skeleton-api:$CIRCLE_BUILD_NUM

      # store raw contents of src code
      - store_artifacts:
          path: target/classes
          destination: my-walking-skeleton
      - run:
          name: Setup Heroku
          command: |
            chmod +x .circleci/setup-heroku.sh
            .circleci/setup-heroku.sh
      - run:
          name: Deploy to Heroku
          command: |
            cd app/
            git push heroku master
